### ISSUE TITLE
Is there a way in eth_addr.circom the output of the address to be string instead of BigInt?

### ISSUE THREAD

**Issue by gmisiakoulis** [0xPARC/circom-ecdsa#32]
Hello, I managed to run eth_addr.circom, but the output is in BigInt. Is it possible or are there any template that transform the BigInt to String? 

For example the address of a private key in eth_addr.circom template is: ``388937196676651799135513985478953745031396740769``, but i want it to be represented as: ``0x44208c0dcb8f242aa4ac0ed13d14c0ef660a4ea1``, or even checksum: ``0x44208C0dcb8F242aa4ac0ed13d14C0Ef660A4Ea1``

Is that feasible?

Thanks in advance

**Comment by UIZorrot** [comment]
It was impossible for a circom circuit to output anything outside a finite field number, so you should make the conversion by yourself.

**Comment by gmisiakoulis** [comment]
perfect, thank you.

**Comment by gmisiakoulis** [comment]
perfect, thank you.
